spring:
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
